### ISSUE TITLE
How can I get the 'videoProcess' module?

### ISSUE THREAD

**Issue by MALLLLLLL** [SillyPasty/bodyPositionProcess#1]
The program is switched on. But there is no body Position detection, and there is no data stored in database. Whether there is a need for our own programming to realize the 'videoProcess' module?  How can I get the 'videoProcess' module?

**Comment by wangyb-A** [comment]
Sorry, we had refactored our code during this spring, and because of the Covid-19, we can not go back to our school and some parts of our code are stored there, which is unreachable so far.
